Repository team-sixteen/gyulgyulmarket, pull requests merged in 2022-01, with the labels that each got.

#11 Profile 팔로우 css 내용 추가
  profile.html
  src/style/style.css
Labels: enhancement

#16 [fix] 오타 수정
  join_email.html
  login.html
  setting_profile.html
Labels: bug

#15 [Add] profile 상단 css styling
  modules.html
  profile.html
  profile_list.html
  profile_modification.html
  src/images/post-img/iccon-img-layers.png
  src/images/post-img/post-img-1.png
  src/images/post-img/post-img-2.png
  src/images/post-img/post-img-3.png
  src/images/post-img/post-img-4.png
  src/images/post-img/post-img-5.png
  src/images/post-img/post-img-6.png
  src/images/post-img/post-img-7.png
  src/images/post-img/post-img-8.png
  src/images/post-img/post-img-9.png
  src/images/profile-img/Ellipse 1.png
  src/images/profile-img/Ellipse 2.png
  src/images/profile-img/Ellipse 3.png
  src/images/profile-img/Ellipse 4.png
  src/images/profile-img/Ellipse 5.png
  src/images/profile-img/Ellipse 6.png
  src/images/profile-img/Ellipse 7.png
  src/style/profile.css
  src/style/profile_list.css
  src/style/profile_modification.css
  src/style/style.css
Labels: enhancement

#18 Lahee/feature/login 404에러 페이지 & 채팅 리스트 페이지
  404.html
  chatlist.html
  profile.html
  profile_list.html
  src/images/404.png
  src/style/404.css
  src/style/chatmodule.css
  src/style/common.css
  src/style/profile.css
  src/style/reset.css
  src/style/style_module.css
Labels: enhancement

#22 [feat] profile UI 변경
  profile.html
  src/style/profile.css
Labels: bug

#21 [add] 상품 업로드 페이지 추가
  product_add.html
  profile.html
  src/style/product_add.css
Labels: enhancement

#25 [add] modal CSS 마크업
  .DS_Store
  modules.html
  profile.html
  profile_list.html
  src/.DS_Store
  src/js/follow/follow.js
  src/style/style_module.css
Labels: enhancement

#26 Lahee js
  chatroom.html
  followers.html
  followings.html
  home.html
  index.html
  profile.html
  src/js/chatRoom.js
  src/js/home.js
  src/js/your-profile.js
  src/style/chatRoom.css
  src/style/common.css
  src/style/home.css
  src/style/style_module.css
Labels: enhancement

#28 Lahee js
  profile.html
  src/js/your-profile.js
  src/style/common.css
Labels: enhancement

#29 Lahee js
  src/style/index.css
  src/style/profile.css
  src/style/style_module.css
Labels: enhancement

#32 Lahee js
  profile.html
  src/js/your-profile.js
  src/style/profile.css
  src/style/style_module.css
Labels: enhancement

#35 Lahee js
  chatroom.html
  home.html
  profile.html
  src/style/chatRoom.css
  src/style/home.css
  src/style/style_module.css
Labels: documentation

#37 Lahee js
  chatlist.html
  home.html
  profile.html
  src/style/style_module.css
Labels: documentation

#42 Lahee js
  __.html
  chatmodule.html
  followers.html
  followings.html
  home.html
  mod_product.html
  my_profile.html
  productTest.html
  profile.html
  src/js/common/navMenu.js
  src/js/follow/follow.js
  src/js/followers.js
  src/js/followings.js
  src/js/home.js
  src/js/my-profile.js
  src/js/utils/slide.js
  src/js/your-profile.js
  src/style/profile.css
  src/style/reset.css
Labels: enhancement

#45 [feat] tab하단 링크 연결 및 색상 변경
  .DS_Store
  home.html
  src/js/my-profile.js
  src/js/your-profile.js
  src/style/profile.css
  src/style/style_module.css
Labels: enhancement

#47 [add] my_profile 링크 변경
  home.html
  profile.html
Labels: enhancement

#40 [add] modal js 추가
  .DS_Store
  profile.html
  splash.html
  src/.DS_Store
  src/js/modal.js
  src/js/splash.js
  src/style/profile.css
  src/style/splash.css
  src/style/style_module.css
Labels: enhancement

#49 [add] 세부 오류 해결
  chatroom.html
  followers.html
  followings.html
  home.html
  index.html
  src/images/error.png
  src/js/followers.js
  src/js/followings.js
  src/js/your-profile.js
  src/style/home.css
  src/style/index.css
  src/style/profile.css
  src/style/style_module.css
  src/style/upload.css
Labels: enhancement

#50 [feat] home feed 구현
  chatlist.html
  chatroom.html
  followers.html
  followings.html
  home.html
  post.html
  profile.html
  src/js/home.js
  src/style/home.css
  src/style/style_module.css
Labels: enhancement

#52 [merge] + [fix] z-index
  .DS_Store
  add_product.html
  home.html
  src/.DS_Store
  src/js/home.js
  src/style/home.css
  src/style/modal.css
  src/style/my_profile.css
  src/style/style_module.css
  src/style/upload.css
Labels: enhancement

#56 [add] home링크 추가
  profile.html
Labels: enhancement
